### ISSUE TITLE
Lint kubectl interpolated blueprint output

### ISSUE THREAD

**Issue by adelbertc** [getnelson/nelson#109]
`kubectl apply -f ... --dry-run`

**Comment by timperrett** [comment]
@adelbertc should we extract this in the /v1/stack inspection api or the blueprints api?

**Comment by adelbertc** [comment]
@timperrett I was thinking this would be used to check blueprints much the same way we lint manifests, so in the blueprints API - wdyt?

**Comment by timperrett** [comment]
Yeah I'm fine with that. I'd actually really like to get this implemented ASAP.
