### ISSUE TITLE
Pijul/Sanakirja Support

### ISSUE THREAD

**Issue by no-identd** [getnelson/nelson#189]
Imagine what you could do if, in addition to git (which pijul generalizes anyway!), Nelson also supported pijul.

Especially with the patching patches feature added in pijul 0.11:
https://discourse.pijul.org/t/patching-patches/212

For why I mention Sanakirja, see here:

https://pijul.org/2017/03/16/sanakirja/

**Comment by timperrett** [comment]
Hi there, thanks for your interest in the project. Unless there is a user who really wants this integration, i'm reluctant to add it unless someone has a burning use case. The VCS part of Nelson is non-trivial, and whilst you could implement this as another interpreter for the free algebra, it would expand our testing surface area significantly and we'd have no way to easily check for regressions.
