### ISSUE TITLE
Move repo to the `getnelson` organization 

### ISSUE THREAD

**Issue by timperrett** [getnelson/nelson#51]
- [x] Update documentation
- [x] Remove all references to the old organization
- [ ] What about artifact publishing? should we continue to publish under the io.verizon org. We don't actually use the JARs so that's something we should talk about. 
- [ ] What about the docker hub repository?
- [x] Moving the repo may or may not break the build (needs investigation)

**Comment by rossabaker** [comment]
I don't think it's wise to count on write access to Verizon's repositories after write access to the project is no longer strictly administered by Verizon.  This move implies repo moves in my mind.

**Comment by adelbertc** [comment]
Seems like checkboxes 1, 2, and 5 are done. Should talk about 3 and 4.. and we still have that Gitter move I assume the Gitter folks haven't responded to yet. Bah.

I'm inclined to agree with Ross which probably means we need to either register a domain or just use `io.github.getnelson`.
