### ISSUE TITLE
Port to cats-based stack

### ISSUE THREAD

**Issue by rossabaker** [getnelson/nelson#54]
We are on a precarious stack of EOL'ed versions of libraries.  With cats-1.0 on the horizon, this is a good opportunity to get current.

Direct dependencies that need a cats-1.0 release:

* [ ] quiver
* [ ] helm
* [ ] knobs
* [ ] http4s
* [ ] doobie
* [ ] argonaut

**Comment by rossabaker** [comment]
There will also be a massive amount of work on Nelson itself, particularly with the `Free` algebras and eliminating `\/` and replacing `Task`.  This won't be quick.

**Comment by adelbertc** [comment]
Knobs PR: https://github.com/Verizon/knobs/pull/57

**Comment by adelbertc** [comment]
@rossabaker Unsure if you still have bandwidth given your new employment, but could you jot down some notes on what's done, what needs doing, etc? I'd like to start working on this soon :-)

**Comment by rossabaker** [comment]
I started by trying to run the scalaz to cats Scalafix. That takes care of
Either migration.

Then there is still a lot that is boilerplate.  Free is a major point.
That's where I hit a fork in the road.  I haven't worked out the best
workflow for this iterative improvement yet.

Knobs and Helm are still in limbo because I was waiting for a final fs2,
and that's hung up on a transform bug right now.

**Comment by adelbertc** [comment]
Done as of:

* https://github.com/getnelson/nelson/pull/64
* https://github.com/getnelson/nelson/pull/70
* https://github.com/getnelson/nelson/pull/71
* https://github.com/getnelson/nelson/pull/72
* https://github.com/getnelson/nelson/pull/75
