### ISSUE TITLE
Add resource requests to manifest file

### ISSUE THREAD

**Issue by adelbertc** [getnelson/nelson#66]
Currently Nelson's CPU and memory specs are resource limits, an upper bound on how many resources a deployment can be allocated. Similarly useful is a resource *request*, a lower bound on how many resources a deployment needs to function properly.

My current plan is to add this as an optional parameter to the current V1 manifest, defaulting it to be equal to the corresponding resource limit when not specified.

One question I have is during parsing/validation time we have some choices to make.. it is possible for the author to specify a resource **request** but not a resource **limt**. Currently resources limits have a default value (0.5 CPU, 512 MB memory), so I see two choices here:

1. Allow users to specify a request without a limit, and validate the specified request is less than the Nelson-provided default. This may make the code a bit trickier, I imagine we have to bubble up the default values [from the scheduler](https://github.com/getnelson/nelson/blob/master/core/src/main/scala/scheduler/NomadHttp.scala#L355-L356) to the validation logic so other parts of the validation can use it. Another option is to make an ADT that is either some symbolic default value that scheduler interpreters are free to interpret on their own, or a user-specified value.

2. Disallow users to specify a request without a limit - fail the validation if this happens.

@timperrett ?

**Comment by adelbertc** [comment]
@timperrett Ping :-)

**Comment by timperrett** [comment]
@adelbertc sorry for the delay. Here we should go for `2` I think. `1` seems overly complicated and doesn't really get us anything logically better.
